### ISSUE TITLE
TCP-session of HTTP/2 instead of session cookie, is it possible?

### ISSUE THREAD

**Issue by ArsenShnurkov** [prepare/WebServerStudy#1]
1) http2-katana supports HTTP/2
https://github.com/MSOpenTech/http2-katana

2) FF supports HTTP/2 since v36

So,
http://stackoverflow.com/questions/30825038/how-to-use-http-2-connection-instead-of-session-cookies

?

**Comment by prepare** [comment]
I will investigate it

**Comment by prepare** [comment]
I  followed your stackoverflow link above,
I think Leif Hedstrom's answer is right :)
